-- 코드를 입력하세요
SELECT YEAR(S.SALES_DATE) AS YEAR, 
    MONTH(S.SALES_DATE) AS MONTH,
I.GENDER, COUNT(DISTINCT S.USER_ID) AS USERS FROM ONLINE_SALE S
JOIN USER_INFO I
ON S.USER_ID = I.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;