-- 코드를 입력하세요
SELECT TITLE, B.BOARD_ID, REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD as A, USED_GOODS_REPLY as B
WHERE A.BOARD_ID = B.BOARD_ID
AND A.CREATED_DATE LIKE "2022-10%"
ORDER BY B.CREATED_DATE,TITLE